# secrets.yml
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  env_key: 'blahblahtoken'
  mailer_options:
    host: "lvh.me"
    port: 3000
  smtp:
    address: "localhost"
    port: 1025
    user_name: ''
    password: ''
    enable_starttls_auto: false
    authentication:
  secret_key_base: '382ef91c01835ed5ba567a367ff1a54cee0e360c579a93181c366d009ca8a34d733c781ae30c830e9c681806bb2839b69e1cca4a2f9c4db4647ea9ea2d7bab78'
  sidekiq:
    username: 'username'
    password: 'password'

test:
  mailer_options:
    host: "lvh.me"
    port: 3000
  smtp:
    address: "localhost"
    port: 1025
    user_name: ''
    password: ''
    enable_starttls_auto: false
    authentication:
      
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  env_key: ''
  mailer_options:
    host: "forbinary.com"
    port:
  smtp:
    address: "email-smtp.us-west-2.amazonaws.com"
    port: 587
    user_name: 'user_name'
    password: 'password'
    enable_starttls_auto: true
    authentication: "login"
